name: maven build & test
on:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          BUCKET: ${{ secrets.BUCKET }}
          URL_DURATION: 10
        run: mvn package
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BUCKET: ${{ secrets.BUCKET }}
      URL_DURATION: 10
    steps:
      #clone the repo
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          BUCKET: ${{ secrets.BUCKET }}
          URL_DURATION: 10
        run: mvn --batch-mode clean test
